[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "financial-core"
version = "0.1.0"
dependencies = [
  "httpx>=0.27",
  "pydantic>=2",
  "pandas>=2",
  "numpy>=2",
  "scipy>=1.12",
  "tenacity>=9",
  "pyarrow>=17",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["core*"]